.gitignore
publications-1998.bib
publications-1999.bib
publications-2000.bib
publications-2001.bib
publications-2002.bib
publications-2003.bib
publications-2004.bib
publications-2005.bib
publications-2006.bib
publications-2007.bib
publications-2008.bib
publications-2009.bib
publications-2010.bib
publications-2011.bib
publications-2012.bib
publications-2013.bib
publications-2014.bib
publications-2015.bib
publications-2016.bib
publications-2017.bib
publications-2018.bib

Add the initial lists of publications (as scraped directly off the website's current publication.html).

Initial publication list

---

Makefile
jabref-template/listrefs.begin.layout
jabref-template/listrefs.end.layout
jabref-template/listrefs.layout
jabref-template/listrefs.misc.layout

- simple version stolen from ASPECT
- uses the jabref inside a docker container
- builds ``publications.html``
We probably need to edit/replace the layout, but this at least "works".

Add html generation

---

publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib

This corresponds to the data in the file `new-references.txt`

Add new entries (and fix some existing ones) using Timo's curated list

---

Jenkinsfile

- skip permission test when on master
- rename stage

Jenkins: also test master

---

publications-1998.bib
publications-1999.bib
publications-2000.bib
publications-2001.bib
publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib

remove owner and timestamp

---

Jenkinsfile

jenkins: check for non-ascii chars

---

README.md

As mentioned in #40. Competes with #43.

Also update the README file about theses.

---

publications-2012.bib
publications-2013.bib
publications-2017.bib

Fix a few thesis entries.

---

publications-2018.bib

- missing number
- nicer key
- nicer order

improve dealii90 entry

---

publications-2018.bib

Some entries.

---

Jenkinsfile

also fix whitespace while we are here.

CI: mark failure status correctly

---

publications-2018.bib

add theses from Clemson

---

jabref-template/listrefs.begin.layout

this is for the dealii.org website. As discussed in #26. See http://dealii.org/temp.html for a demo (in about an hour)

move plot to top of page in html

---

jabref-template/listrefs.begin.layout
jabref-template/listrefs.end.layout

This is an attempt at getting us in the right direction with regard
to the currently pretty broken layout of the page. I don't quite know
yet what the issue is, but I hope to get closer to it in increments.

Adjust layout.

---

publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib

Add a bunch more.

---

publications.include

These are shown pre-formatted, so formatting matters.

Fix the indentation of a couple of bibtex entries.

---

README.md

Add reference to doi2bib.org in the README.md

---

publications-2018.bib
publications-2019.bib

Add a few.

---

publications-2017.bib
publications-2018.bib

Add two preCICE theses.

---

publications-2018.bib
publications-2019.bib

Fixes #87. Fixes #93. Fixes #92.

Add a few more.

---

publications-2019.bib

This one has pretty cool pictures :-)
It's only available online right now, so no volume or page numbers. But it has the DOI, so should be easy to find and update later on if we want.

Add another paper.

---

publications-2018.bib
publications-2019.bib

Eight publications were added to the 2018 and 2019 BIB files.

Resolved issue #90

---

publications-2018.bib

Six new BibTeX entries were added
Umlauts fixed (rebuilt pull request)
There was an umlaut that was showing as an invalid character. Fixed that.
Another Umlaut
Parsing error fixed

Added Publications

---

publications-2019.bib

This adds a paper that I look forward to reading at one point!

Add the paper about DFT-FE.

---

publications-2018.bib
publications-2019.bib

I deleted these from the google doc, and also removed a couple that didn't
use deal.II at all.

Some of the publications from Timo's list.

---

Makefile

add make target latex

---

jabref-template/listrefs.misc.layout

My attempt at #134. I'll admit that I don't expect anyone to understand this (jabref entries are black magic) -- would appreciate merging and then I'll see how this look in the online version and iterate if necessary.

Attempt to correctly format arXiv entries.

---

jabref-template/listrefs.misc.layout

#136 did not do the trick. Let's try this one instead.

Update arXiv output template.

---

publications-2017.bib

The missing year breaks https://www.dealii.org/publications.html
Fix this.

fix missing year

---

publications-2019.bib

Took us long enough to get this written and submitted :-)

Add a preprint.

---

publications-2016.bib
publications-2019.bib

Add more from Timo's list.

---

publications-2017.bib
publications-2018.bib
publications-2019.bib

In particular, update a few and remove duplicates. Some were in the file
for the wrong year.

Clean up the entries of 2017 and 2018.

---

publications-2020.bib

It is in press, but can already be retrieved.

Open 2020 with one

---

publications-2019.bib
publications-2020.bib

Update a publication that has now appeared.

---

publications-2020.bib

Add hyper.deal release paper

---

publications-2016.bib

Add a DOI.

---

publications-2018.bib
publications-2019.bib

First updates from Timo's list.

---

publications-2016.bib

Not sure exactly how this is going to come out -- let's see.

Add a thesis from 2016.

---

publications-2017.bib
publications-2018.bib

Updated incomplete entries, moved entries to correct year

Updated entries

---

publications-2016.bib
publications-2017.bib
publications-2020.bib

Added and extended some theses from Forschungszentrum Jülich.

Juelich publications

---

publications-2018.bib
publications-2019.bib
publications-2020.bib

I finished my Ph.D. last year at University of Bergen and here are my contributions using deal ii.
My latest paper "MB_paper_C" is finally published .

My awesome phd work

---

publications-2019.bib

This is the replacement for #218. It contains everything that was in #218, plus a unicode fix.

Update a bunch of entries.

---

publications-2018.bib

Remove a duplicate entry.

---

publications-2019.bib

As far as I can tell, the deletions are due to my text editor having slight formatting differences. It looks like tabs were used previously (possibly by me) and they were converted to spaces.

Added 2019 arXiv preprint publications.

---

publications-2019.bib

Add several entries to the 2019 list.

---

publications-2017.bib

I really don't know whether that makes a difference, but thought it's worth doing while I was in that file anyway. That's my kind of OCD.

Spell out the initials of an author.

---

publications-2019.bib

Other article types such as dissertations from 2019 (plus one or two normal articles which I missed previously).

2019 Citations

---

publications-2018.bib

Some of the citations have the same label. I'm unsure how big of an issue this is, as that was also the case in some previously finished citations as well

Added more entries

---

publications-2020.bib

Popular article about this study (140k reads!): 
https://www.esa.int/Applications/Observing_the_Earth/Swarm/Swarm_probes_weakening_of_Earth_s_magnetic_field

Add a paper

---

publications-2018.bib

remove duplicates

---

publications-2020.bib

Thanks to the maintainers for this wonderful library.

Added entry Cobb2020

---

offline/publication_list.tex
publications-2021.bib
publications.include

I will update the .include separately.

add 2021.bib and add one

---

publications.include

The new paper is now fully out. Let's make sure that people cite that one and not the old one.
/rebuild

Retire the 2007 paper.

---

publications-2018.bib
publications-2019.bib
publications-2020.bib

Fix \textendash problem.

---

publications.include

Update a reference

---

publications-2018.bib

I was told that the article doesn't actually show results obtained with deal.II.
/rebuild

Remove an article that doesn't use deal.II.

---

publications-2016.bib
publications-2018.bib
publications-2020.bib

Should both preprints and published versions be listed here? The published paper in my second commit is already listed as a preprint. Should I remove the preprint or leave it?

Add two of my papers published in 2020

---

publications-2017.bib
publications-2019.bib
publications-2020.bib
publications-2021.bib

Add three more

---

publications-2020.bib

Worked on my own issue #284 from yesterday and inserted publications myself.

twick update pubs 2020

---

publications-2021.bib

twick update pubs 2021

---

publications-2021.bib

EnTechnol Articles

---

publications.include

we might want to wait until it is available online, but here is the PR already.

add 9.3 paper

---

publications.include

Add a DOI to the 9.3 release paper.

---

publications-2019.bib

Fix an entry.

---

publications-2019.bib

The ones I'm removing are in the database twice.
/rebuild

Fix a couple more 2019 entries.

---

publications-2019.bib

delete duplicate entry

---

publications-2014.bib
publications-2018.bib
publications-2019.bib
publications-2020.bib

This is covers most of the publications listed in the second half of our googledoc. I will add the remaining ones in a later PR.
I cleaned up duplicated entries on the way.
Further for each publication, I took the date when it was published online, not the date the actual journal issue got published. The reason is that doi2bib.org prepares entries like this.

Added citations to various collected publications.

---

publications-2018.bib
publications-2019.bib
publications-2020.bib
publications-2021.bib

add publications

---

publications-2014.bib

Complete two older entries.

---

publications-2014.bib
publications-2015.bib
publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib
publications-2020.bib
publications-2021.bib

ASPECT publications are deal.II publications as well.

---

publications-2021.bib

Add one entry.

---

publications.include

Add a missing comma.

---

publications-2019.bib
publications-2021.bib

Add and update.

---

publications-2021.bib
publications.include

Update 9.3 entry.

---

publications-2021.bib

Finally I have published my phd thesis.

Add entry castelli2021numerical

---

publications-2021.bib

Add entry castelli2021parallel

---

publications-2019.bib

Add entry castelli2019efficient

---

publications-2022.bib

Add first publication of 2022.

---

publications-2017.bib

She was a Master's student visiting the Guest Student Program at JSC which I supervised at that time. I didn't know she based her whole thesis on deal.II. So I'll add it to our list :)

Added Master's thesis of Duygu Kan.

---

publications-2021.bib

The defense is going on as about to happen as I write this :-)
/rebuild

Add Rigsby's MS thesis.

---

publications-2012.bib

Added Kronbichler2012.

---

publications-2018.bib
publications-2020.bib

Fixes #90.
See https://github.com/dealii/publication-list/issues/90#issuecomment-1053716638 for details.

Cleanup 2018 publications. Add one entry for 2020.

---

publications-2008.bib
publications-2012.bib
publications-2013.bib
publications-2014.bib
publications-2015.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib
publications-2021.bib
publications.include

Part of #289.
This covers the `accepted` publications. There are still plenty of publications flagged as `submitted` that need to be updated, too, but let's do this in a separate PR.
---
I couldn't find this entry anywhere. If you google it, you can only find it on our publication page. Shall we remove it?
https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2011.bib#L538-L548
---
This appears to be a talk. I can also only find it on our website and on [LinkedIn](https://za.linkedin.com/in/michael-rapson-95651344). Shall we remove it too?
https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2011.bib#L527-L536

Update `accepted` publications.

---

publications-2011.bib

There is no evidence of existence of these entries.
See https://github.com/dealii/publication-list/pull/341#issue-1153555759.

Removed Rapson2011.

---

publications-2022.bib

Fixed Salvador2022.

---

publications-2022.bib

Add another fascinating one.

---

publications-2022.bib

Added "An efficient and accurate implicit DG solver for the incompressible Navier‐Stokes equations" publication published online in "International Journal for Numerical Methods in Fluids". The corresponding code has been submitted for a pull request in the "code-gallery"

Added new publication for 2022

---

publications-2018.bib
publications-2019.bib

Replace the two by the normative one.
/rebuild

Fix a duplicate entry.

---

publications-2021.bib
publications-2022.bib

There were three references made using Lethe (thus using deal.II) that were not added to the publication list. I added them :).

Add three references

---

publications-2021.bib
publications-2022.bib

Appended the items to the respective files.

Added 4 bibitems in 2021.bib and 2022.bib

---

publications-2020.bib
publications-2021.bib
publications-2022.bib

These are new or missing publications of the research group of @tommeswick .

Updates for research group Wick

---

publications-2022.bib

Added aggul2022.

---

publications-2016.bib
publications-2019.bib
publications-2020.bib
publications-2021.bib
publications-2022.bib

Removed some preprints, and added actual publications, with links and dois.

Updated publications by LH.

---

publications-2017.bib

Already present here:
https://github.com/dealii/publication-list/blob/a298a6f4408fb9a7b00b11fc058e39bbebb35378/publications-2018.bib#L1370-L1382
https://github.com/dealii/publication-list/blob/a298a6f4408fb9a7b00b11fc058e39bbebb35378/publications-2019.bib#L170-L181
https://arxiv.org/abs/1709.04052

Remove duplicates.

---

publications.include

Fix character.

---

publications-2022.bib

- Added an url in which the thesis can be consulted
- Added month
- Changed Bachelor's Thesis from 'type' to 'note' as seen in the repository advice (It appears in the web as Master's Thesis, but it is a Bachelor's Thesis)

Modified entry lorencioabriljoseantonio2022

---

publications-2022.bib

Corresponding to https://github.com/geodynamics/aspect/pull/4933.
/rebuild

Two new ones.

---

publications-2022.bib

fyi @kronbichler @nfehn @peterrum

Adds entry Wik1676116

---

offline/publication_list.tex
publications-2020.bib
publications-2021.bib
publications-2022.bib

Update publications from MOX

---

publications-2019.bib

Building the publication list locally reveals that we have lots of duplicate keys:
```
WARN - Duplicate entry key: 'Arbogast2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Guo2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Hagstrom2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Balicki2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'EbnaHai2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Bzowski2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Freddi2019' in file '../publications-2019.bib', skipping ...
WARN - Duplicate entry key: 'Alarydah2019' in file '../publications-2019.bib', …
```

Fixed duplicate entry keys for 2019.

---

Jenkinsfile

based on conversation in https://github.com/dealii/publication-list/pull/385#issuecomment-1235675330

CI: fail if duplicates found

---

publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib

`biber` complained about a few more duplicates.
~I don't know how it managed to identify them. Have a look at the duplicate entry from the 2017 list. Lots of the fields are similar, but none of them except the `pages` field matches character by character. I'm impressed.~
EDIT: It's actually just checking bibtex keys. There was a matching key in the previous year. It was just coincidence that I found another duplicate.

Removed few more duplicates.

---

publications-2021.bib
publications-2022.bib

This 2022 entry was in the 2021 file.

Move an entry.

---

publications-2014.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib
publications-2020.bib

Closes #79. ~Blocked by #407.~ (EDIT: Has been merged.)

Publications of issue #79.

---

publications-2020.bib
publications-2021.bib
publications-2022.bib

~Blocked by #407.~ (EDIT: Has been merged.)
While going through the articles in #283, I've supplemented the information we didn't have in our system yet.

Added publications of Thomas Wick.

---

jabref-template/listrefs.book.layout
jabref-template/listrefs.inproceedings.layout
jabref-template/listrefs.layout
jabref-template/listrefs.mastersthesis.layout
jabref-template/listrefs.misc.layout
jabref-template/listrefs.phdthesis.layout

As requested in https://github.com/dealii/publication-list/pull/407#issuecomment-1247538629.

Use 'Preprint' in jabref.

---

publications-2020.bib

Add the first few from the 2020 list.

---

publications-2019.bib
publications-2020.bib
publications-2021.bib
publications-2022.bib

Minor changes.

---

publications-2020.bib

Added publications C-F.

---

publications-2018.bib
publications-2020.bib

I was doing a final cleanup after the last changes. I removed the whitespaces around the braces and noticed that I apparently missed to call `make sort` at one point as one entry was not at the correct spot.

Cleanup: removed whitespaces around braces.

---

publications-2020.bib
publications-2021.bib

Two of those are actually in 2020.

Add first 4 from the 2021 list.

---

publications-2020.bib
publications-2021.bib
publications-2022.bib

Added 2021 publications A-E.

---

publications-2021.bib

We had trouble with this character in the past, see #384.

Prevent possible problems with \i

---

publications-2022.bib

Update iHeart publication.

---

publications-2022.bib

Added iheart pub.

---

publications-2022.bib

Add entry 2022:castelli.dorfler:comparison

---

bibtool.rsc

I am just playing around with bibtool for my own repo and found this.

Fix bibtool.rsc comment line

---

publications-2004.bib

I am just trying things for #479 and found this. Maybe @bangerth knows best about this publication?!

Fix entry 2004:bangerth:framework

---

publications-2022.bib

Also uses aspect as the title suggests :)

Add one preprint.

---

publications-2021.bib
publications-2022.bib

This article uses GoFEM and cites deal.II.
@agrayver -- Can you confirm you were using deal.II?

Add three.

---

Jenkinsfile
docker/Dockerfile
docker/make.sh
docker/push.sh
docker/test.sh
publications-2021.bib

- new docker image with updated libraries
- include all information to make the docker image
- correct .pdf compilation using latexmk
- report all warnings report by biber

CI: update docker image

---

publications-2022.bib
publications-2023.bib

New entry of a published article. The preprint version is present in the 'publications-2022.bib' file, so I do not know if this is the correct way to update it

Added entry 2023:orlando.benacchio:imex

---

publications.include

Addressing https://github.com/dealii/dealii/pull/15290#discussion_r1212231629.

Remove 9.3 from the list of suggested publications to cite

---

publications-2021.bib
publications-2022.bib
publications-2023.bib

The looks like the proceedings will be published in 2023:
http://www.ddm.org/DD26/Proc-26.php

Update three publications of Wick.

---

publications-2022.bib
publications-2023.bib

Added 7. Updated 2.

---

publications-2023.bib

Add a 2023 publication citing deal.II from our research group.

Add new publication using/citing dealii

---

publications-2016.bib
publications-2018.bib
publications-2019.bib
publications-2020.bib
publications-2021.bib
publications-2022.bib
publications-2023.bib

Closes #531.
As stated in https://github.com/dealii/publication-list/issues/531#issuecomment-1681381878, some articles do not refer to deal.II, but the author explicitly mentioned them to be included.

Add publications by Mustafa Ağgül

---

publications-2022.bib
publications-2023.bib

Added 6. Updated 2.

---

publications-2011.bib
publications-2014.bib
publications-2015.bib
publications-2017.bib

Follow-up to https://github.com/dealii/publication-list/pull/536. Part of https://github.com/dealii/publication-list/issues/289.
Some various updates of entries that I stumbled over.
Found another thesis after looking up a preprint with the same name, which is nice.

Miscellaneous updates.

---

publications-2009.bib
publications-2010.bib
publications-2012.bib
publications-2014.bib
publications-2015.bib
publications-2016.bib
publications-2017.bib
publications-2018.bib
publications-2019.bib
publications-2021.bib

Part of #289.
About a year ago, I started my mornings updating arxiv entries in our publication database to help me wake up. I stopped at the year 2018 for whatever reason, and I just rediscovered this stale branch.
So I spent a couple of minutes to rebase and sort out my commits to integrate my previous efforts to the database. I have a few other housekeeping commits from that time, which I would address in separate pull requests.

Update arxiv publications 2009 - 2017.

---

offline/publication_list.tex

See also: https://tikz.dev/pgffor
Result: https://ci.tjhei.info/job/publication-list/job/PR-541/1/artifact/offline/publication_list.pdf

Use foreach loop in offline tex.

---

publications-2011.bib
publications-2022.bib

More 2022 publications.

---

publications-2005.bib
publications-2011.bib
publications-2013.bib
publications-2018.bib
publications-2020.bib
publications-2021.bib
publications-2022.bib

Follow-up to https://github.com/dealii/publication-list/pull/549, https://github.com/dealii/publication-list/pull/551, https://github.com/dealii/publication-list/pull/553 - #556

Even more 2022 publications.

---

publications-2021.bib
publications-2022.bib
publications-2023.bib
publications-2024.bib

Add the latest ASPECT publications.

---

publications-2019.bib

Add a missing ASPECT publication.

---

publications-2022.bib
publications-2023.bib

Add publications by Hebner.

---

publications-2022.bib

Add Thomas's book.

---

jabref-template/listrefs.incollection.layout

Add a format for @InCollection.

---

publications-2022.bib
publications-2023.bib
publications-2024.bib

This corresponds to https://github.com/geodynamics/aspect/pull/5510.

Add the next batch of ASPECT papers.

---

publications-2023.bib

Add one of the two publications from https://github.com/geodynamics/aspect/pull/5544 (the other one was already in the list).

Add one more ASPECT publication.

---

publications-2024.bib

Update from https://github.com/geodynamics/aspect/pull/5663/files

Import ASPECT publications.

---

publications-2024.bib

Taken from https://github.com/geodynamics/aspect/pull/5806. (That PR also updates one publication, but we already have that correctly in our database.)

Take over two from the ASPECT folks.

---

publications-2023.bib
publications-2024.bib

I have now 
(1) Changed the months to have three characters only
(2) The urls have been removed from the dois
Thank you

Narasimhan 2604 my publication

---

publications-2022.bib
publications-2023.bib
publications-2024.bib

Adds the ones from https://github.com/geodynamics/aspect/pull/5993 and https://github.com/geodynamics/aspect/pull/5968.

Update recent ASPECT publications.

---

publications-2007.bib
publications-2008.bib
publications-2018.bib
publications-2019.bib

..., i.e., change the entry to the publisher's DOI.

Fix bibtex entry for Oberwolfach Reports.

---

publications-2022.bib
publications-2023.bib
publications-2024.bib
publications-2025.bib

Down to Zwaan et al. (2025), 'Rift-inversion...' in the ASPECT master publication list.

Add recent ASPECT-based publications.

---

publications-2024.bib
publications-2025.bib

There are 8 articles in the proceedings to ENUMATH 2023 which cite deal.II!

Added 12. Update 1.

---

publications-2013.bib
publications-2014.bib
publications-2015.bib
publications-2025.bib

Some entries for ENUMATH 2013 were in the wrong year. Found a duplicate this way.

Move proceedings to correct year.

---

publications-2025.bib

Take over https://github.com/geodynamics/aspect/pull/6286

Add an ASPECT publication.

---

publications-2019.bib
publications-2020.bib
publications-2021.bib
publications-2022.bib
publications-2023.bib
publications-2024.bib

@ljhwang found many more ASPECT papers. This PR copies them to the deal.II repo as well.

Add many more ASPECT papers.

---

publications-2020.bib
publications-2021.bib
publications-2022.bib
publications-2023.bib
publications-2024.bib
publications-2025.bib

After a first review of the 2023 publication list, I found inconsistencies in our current publication list that this PR is correcting.
This PR does not add any new articles. It updates, moves, or removes entries already in our publication list. See commit messages for details.

2023 review

---

publications-2024.bib
publications-2025.bib

Added four entries: <2025:jin:grad-proj-phasefield> <2025:li.chen.jin:coating> <2024:jin.li.chen:lbfgs-phasefield> <2024:jin:magnetoelastic>

Add several publications from Prof. Tao Jin's group at the University of Ottawa, Canada

---

Jenkinsfile
publications-2023.bib

This patch adds 58 additional entries and completes the collection for 2023.

Complete 2023 publications.

---

publications-2023.bib

Closes https://github.com/dealii/publication-list/issues/651

Add 2023 book
