offline/publication_list.tex
This can be built using the command "latexmk publication_list.tex" and
can be used to check that the entries are correctly parsed and emit no
errors.
=> Add latex project to render the bibtex entries offine.

offline/publication_list.tex, publications-1998.bib, publications-1999.bib, publications-2001.bib, publications-2002.bib, publications-2003.bib, publications-2004.bib, publications-2005.bib, publications-2006.bib, publications-2007.bib, publications-2008.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib
Changes Jabref entries to use brackets, guarding against runaway latex commands. Removes unicode and HTML from all entries.
=> Clean up original entries

publications-1998.bib, publications-1999.bib, publications-2000.bib, publications-2001.bib, publications-2002.bib, publications-2003.bib, publications-2004.bib, publications-2005.bib, publications-2006.bib, publications-2007.bib, publications-2008.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib
The encoding is changed from ISO-8859-1 ( https://en.wikipedia.org/wiki/ISO/IEC_8859-1 ), which supports some special characters, to ASCII ( https://en.wikipedia.org/wiki/ASCII ), which does not. The intent is that Jabref will not allow files with special characters to be saved if the encoding does not allow it. This should help with detection if some anomalous characters slip into an entry (e.g. if entries are downloaded from DOI, e-print, etc.).
I understand that this is a bit hostile towards our European colleagues, but I think it will help ensure that all entries are rendered as intended. All special characters will thus need to be explicitly formed with tex commands. If it makes a difference, we already enforce this when `offline/publication_list.tex` is built.
=> Change encoding enforced by Jabref.

publications-2005.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib
The name is generally spelled without a space to the left and right of the ampersand.
=> Fix spelling of 'Texas A&M'.

jabref-template/listrefs.phdthesis.layout
As noted before, theses are printed awkwardly with a leading period. This
can be avoided by having a separate style file for PhD theses. This is a
starting point -- let's see what it renders. If this works, I can add a
similar file for `@mastersthesis` entries.
=> Add a template file for PhD theses.

jabref-template/listrefs.layout
This should print notes such as 'submitted' or 'accepted' or 'in print'
in parentheses after everything else but before the year. In most cases,
submitted/accepted/in print papers don't have a volume and pages yet,
so this will print the note text in parentheses right after the journal.
There are of course going to be cases where there is no journal. In
that case, '(Submitted), 2018' will be all that's printed. That
is going to look a little funny. If one of you don't like it, any
other suggestions?
=> Print 'note' fields.

README.md
A subheading was added in #44, but it erroneously appears as a bullet point. This change fixes that.
=> Fix subheading in README

publications-2017.bib
The final citation is available in the 2019 page so we can delete the preprint reference.
Followup to #60; I thought that looked familiar.
=> Remove a duplicate citation.

jabref-template/listrefs.begin.layout
This statement is responsible for the broken layout of the page. There are
other issues (textual, further layout, etc) that can be addressed in follow-up
PRs, but this is the key to getting the page look halfway reasonable.
=> Remove a 'width:' statement that messes up the page layout.

jabref-template/listrefs.begin.layout, publications.include
This PR does two things:
* The first commit moves the table of contents up to the top row of
boxes. This seems like the better place for it.
* The second commit simply includes the rest of the 'publications.include'
file into the jabref top-of-the-file template. Right now, the contents
of the publications.html are cobbled together from a variety of places:
listrefs.begin.layout, listrefs.end.layout, the publications.include
file that lives in a different repository, and the bibtex database.
This just seems too complicated. The different repositories also
make it difficult to sync changes that would affect files from both
repos, as I do in the first commit. So I decided to just get rid of
the publications.include file.
Once merged, and once the new publications.html file shows up in the …
=> Further layout improvements.

jabref-template/listrefs.begin.layout
This is a follow-up to #72. The current version looks rather awkward
because I forgot to remove a 'height' statement :-(
@tjhei: Apologies for the extra work.
=> Fix layout.

jabref-template/listrefs.misc.layout
#135 almost worked, but I had a typo in the generation or URLs and some odd spacing in another place. Would appreciate merge of this update.
Fixes #134.
=> Fix the generation or URLs for arXiv preprints.

publications-2018.bib
These are all 2018 entries from Timo's list that were found to have used deal.II for their numerical examples.
=> Add the 2018 entries from Timo's list.

jabref-template/listrefs.end.layout
ignore invalid bib entries in the html page (without or with an incorrect year) that would break displaying
the pretty diagram.
=> robust diagram display

Makefile
The local make target for the html page would paste all .bib files in
the folder together, not only the ones that are supposed to exist. Fix
this.
=> Makefile: ignore other bib files

publications-2019.bib
=> Capitalize a first name.

jabref-template/listrefs.inproceedings.layout
Previously, we default template was used, but that looks wonky for some entries.
=> Add an output template for @inproceedings.

publications-2018.bib, publications-2019.bib
this cleans up a few publications where we had only listed preprints, and adds three more publications from 2018/2019 that were missing and are not in #186.
=> Clean up a few publications from 2018

publications-2017.bib, publications-2018.bib
I noticed a few duplicates of my publications (some were preprints and published in 2018/2019, the SISC paper was simply listed twice).
=> Remove some duplicate publications

publications.include
There is a newline at the end of the <pre> block, that looks awkward.
Remove it.
=> remove newline in code block for bibtex entry

publications.include
We don't need the old bibtex here anymore, I think. The link to the
bibtex might be useful, though?
=> replace 9.0 bibtex with link

publications.include
Using more vertical space reduces the visibility of the entries below. Be a bit more
moderate.
=> Use less vertical space for the 9.2 entry.

publications-2016.bib, publications-2017.bib, publications-2020.bib
Follow up to #224.
I just realized that I forgot to add a `,` in Sean's dissertation, and decided to also remove the redundant separators in the other entries.
Sorry about that :(
=> Fix bibtex field separators.

jabref-template/listrefs.end.layout
Specifically: (i) better use the vertical range; (ii) don't show every
year as a label on the x-axis, given that it gets a bit crowded by now.
=> Adjust some options for the graph of publications.

jabref-template/listrefs.end.layout
Turns out that my last PR doesn't actually work -- the graph object just has its own ideas of how you can set the max size. But there is a different parameter one can set, and I'm now setting this parameter to simply the maximum number of publications we've seen per year. That's also future-proof.
Tested locally to actually work, so I have hope that it will also on the website.
=> Find a better way to limit the size of the graph's y-axis.

publications-2018.bib
Specifically, the entry had no year and so showed up at the very top of the list.
=> Fix an entry.

jabref-template/listrefs.layout
Specifically, we have punctuation marks at the beginning of the next entry; here,
we have one at the end and that may lead to two punctuation marks following each other.
=> Fix jabref formatting.

publications-2016.bib, publications-2018.bib
I didn't realize that there are also `emdash` occurrences when writing #270 (see also #267). This fixes the two occurrences.
/rebuild
=> Fix \emdash similarly.

jabref-template/listrefs.book.layout
May fix #285. Certainly doesn't make it any worse, given that `@book` entries don't have most of the fields that the generic entry uses.
/rebuild
=> Add a template for books.

publications-2021.bib
See bottom of https://www.dealii.org/publications.html
The 9.3 entry is listed with a separate "year"
=> Fix year for 9.3 entry.

publications.include
By looking at the publication list, I noticed that in the details section we had no logical nor temporal order in place. I reordered the manually generated list of publications on details of deal.II from most recent to oldest, and added details on a publication that was accepted on ACM.
=> Reorder publications on details of deal.II from most recent to oldest

publications-2022.bib
These two publications currently appear at the very bottom of https://dealii.org/publications.html where there is a section heading "2022, submitted", sorted after 1998.
=> Fix entry years.

publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
- Fix `month` entries (see Q13 of [bibtex FAQ](https://ctan.org/pkg/bibtex?lang=en))
- Fix `doi` entries (no urls)
- Remove `url` if information redundant to `doi` field
- Update preprints if published in the meantime. Let `url` still point to arxiv preprint.
There are tons of additional `arxiv` preprints for previous years through which we need to go. Part of #289.
=> Some housekeeping for 2019 - 2022.

publications-2017.bib, publications-2018.bib, publications-2019.bib, publications-2020.bib
```
! LaTeX Error: Unicode character ́ (U+0301)
not set up for use with LaTeX.
```
That's the corresponding symbol: https://www.compart.com/en/unicode/U+0301
`\i` removes the dot over the i. It appears that combining `\'{\i}` leads to troubles. `\'{i}` yields the desired symbol.
=> Fix unicode error for local builds.

publications-2018.bib
Same as #385, but for 2018
```
WARN - Duplicate entry key: 'Jodlbauer2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Guo2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Deolmi2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Cheng2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Cangiani2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Zhang2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Carreo2018' in file '../publications-2018.bib', skipping ...
WARN - Duplicate entry key: 'Wang2018' in file '../publications-2018.bib', skipping ...
```
=> Fixed duplicate entry keys for 2018.

bibtool.rsc, publications-2001.bib, publications-2003.bib, publications-2004.bib, publications-2005.bib, publications-2006.bib, publications-2007.bib, publications-2008.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
Part of #389. Follow-up to #391.
This PR enables the `sort` feature of `bibtool`. In the previous PR, we only adjusted the citekeys and the general formatting. Now, we enable the default sorting mechanism, which is [sorting by the citekey](https://github.com/ge-ne/bibtool/blob/97fc3d04655c855ca2794c40303b12fee3fbd273/lib/default.rsc#L113).
I haven't checked if all entries are preserved. But a good indicator that we only move code around is that the number of additions equals the number of deletions (plus the two lines in the configuration file).
=> bibtool: enable sorting

bibtool.rsc, publications-2016.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
Part of #389.
This is just a cosmetic change to use braces as delimiters consistently in all bib files.
=> bibtool: use braces instead of double quotes as delimiters

publications-2001.bib, publications-2012.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib
Part of #389.
With some help of bibtool and some additional sed routines, I brought all month entries into the recommended format in the [bibtex FAQ](https://ctan.org/pkg/bibtex?lang=en), Q13.
bibtool has a mechanism to force the three letter abbreviation, but it doesn't cover all possible cases, so I didn't add it to the configuration.
=> use three letter month macros

bibtool.rsc
Part of #389.
This patch lets bibtool automatically take care of non-ASCII characters according to this resource:
https://github.com/ge-ne/bibtool/blob/master/lib/iso2tex.rsc
We already check for these in the `latex` CI stage, but it would be nice to have another level to identify these characters and to automatically get rid of them.
=> bibtool: translate iso characters to latex.

bibtool.rsc
Part of #389.
The resource checks for semantic issues with the year field.
https://github.com/ge-ne/bibtool/blob/master/lib/check_y.rsc
So the current form of our publication list has no issues with the year field as bibtool didn't complain about any.
=> bibtool: semantic checks for year fields.

bibtool.rsc, publications-1998.bib, publications-1999.bib, publications-2000.bib, publications-2001.bib, publications-2002.bib, publications-2003.bib, publications-2004.bib, publications-2005.bib, publications-2006.bib, publications-2007.bib, publications-2008.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
Part of #389. This should fix part 2 of #405.
I've changed the citekey that in starts with the year.
The nice thing about this approach is that the publications are now also sorted by year first, which lets us easily identify articles that are in the wrong file. I moved some articles around in the second commit and found a few duplicates.
=> bibtool: added year to citekey

bibtool.rsc, publications-2001.bib, publications-2002.bib, publications-2003.bib, publications-2004.bib, publications-2005.bib, publications-2006.bib, publications-2007.bib, publications-2008.bib, publications-2009.bib, publications-2010.bib, publications-2011.bib, publications-2012.bib, publications-2013.bib, publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
Part of #389.
Second to last resource I would like to incorporate in our publication list. This sorts the fields inside each bibtex entry.
https://github.com/ge-ne/bibtool/blob/master/lib/sort_fld.rsc
Again, this is an entirely subjective change with the goal to have a more uniform publication list. We can adjust the order in which we want to sort the fields ourselves -- this is just the default that the author of bibtool thinks looks nice.
This patch just moves fields around. You can see that the number of line additions is similar to the number of line deletions (with the difference being the 3 lines in the configuration file).
=> bibtool: sort order for fields.

jabref-template/listrefs.book.layout, jabref-template/listrefs.inproceedings.layout, jabref-template/listrefs.layout, jabref-template/listrefs.mastersthesis.layout, jabref-template/listrefs.misc.layout, jabref-template/listrefs.phdthesis.layout, offline/publication_list.tex, publications-2017.bib, publications-2018.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib, publications-2022.bib
Based on the discussion in https://github.com/dealii/publication-list/pull/382#pullrequestreview-1093840819.
I've added a new field `preprint` to the biblatex datamodel and the jabref templates. Here is the idea:
- Users who do not have access to journal publications can now at least have a look at the preprint (insofar as it is public, e.g. on arxiv).
- If we replace preprints with the published articles in the future, we can still connect the preprint to the article in a clear way without loss of information.
The patch manifests as follows:
- In the online publication list, another link pointing to the preprint the will be displayed. No preprint field will be part of the bibtex entry if you click on the `BIBTEX` button to expand it.
```
\begin{preprint}
[<a href="\format{\preprint}" …
```
=> Added 'preprint' field.

Makefile, bibtool.rsc
Lets `bibtool` exit with error code 1 on the first error encountered.
Otherwise `bibtool` would ignore the entry with the error, which would remove it from the bib file. We don't want that. I learned it the hard way (no bibtex entries have been forgotten since the introduction of `make sort`) :-)
=> bibtool: parse exit on error.

bibtool.rsc
The `iso2tex` resource doesn't work reliably for me: I encountered corner cases where unicode characters got transformed into junk.
Let's disable it before it does any harm!
=> bibtool: Disable iso2tex.

publications.include
This PR adds missing DOIs to the details on deal.II publications. 
Also, `doi.org` is preferred over `dx.doi.org`, see https://www.doi.org/doi_handbook/3_Resolution.html#3.7.3 .
=> Added missing DOIs.

Makefile
The current version in master deletes all the content of the ``publications-*.bib`` files on my machine. With the fix it works.
=> Fix make sort

publications-2022.bib
`article-number` is not a common field in bibtex. [doi2bib](https://www.doi2bib.org/bib/10.3390/geosciences12020050) reports this field as `pages`, so I changed it accordingly.
=> Fix field name.

publications-2022.bib
Add our latest publication: ECCOMAS 2022 proceeding.
=> Add 2022:schoof.castelli.ea:parallelization

publications-2021.bib
See also https://github.com/dealii/publication-list/pull/443#issuecomment-1256704541
The TeX distribution on the CI does not like the Ā character, which we set with `\=A`.
```
! Package inputenc Error: Unicode char \u8:Ā not set up for use with LaTeX.
```
I don't encounter this problem on my machine when running make latex.
Is it time to update the CI? Alternatively, I can turn the character into A without the bar.
=> Unicode :-(

publications-2023.bib
Follow-up to #512.
The `\chi` symbol only works in math mode. We only spotted this after we included the 2023 publications into the global file. So my https://github.com/dealii/publication-list/pull/512#issuecomment-1460121117 was actually wrong.
=> fix symbol

publications.include
The `bibtex` snippet for 9.5 looks ill-formatted. This PR adjust the indentation, plus a few other miscellaneous things.
=> Indent 9.5 paper.

publications-2014.bib, publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib
Follow-up to #536. Part of #289.
I got suspicious when titles of articles clearly referred to other FEM libraries (as DUNE or FEMPAR), so I started to check articles for their content. I found a few that cite deal.II, but do not actually use it, and thus I suggest to remove them.
=> Articles that mention, but do not use deal.II.

publications-2015.bib, publications-2016.bib, publications-2017.bib, publications-2018.bib, publications-2022.bib
After going through some articles in the 2018 publication list, I spotted a couple of duplicates of Mohebujjaman, and many of the URL fields had links that lead to nowhere. I tried my best to update them.
=> Update articles of Mohebujjaman.

publications-2019.bib, publications-2020.bib, publications-2021.bib
Part of #289.
I found another stale branch that I haven't touched since a year or so. This mainly only contained information about preprint fields.
=> Removed three duplicates. Update preprint fields.

scripts/doi2bib.py
This is a short script that creates bibtex entries from a given list of dois. Those dois that this script cannot resolve will be stored separately -- one needs to decide individually what to do with them.
The results are simply written to the terminal, separating resolved and unresolved DOIs to `stdout` and `stderr`, but I am open to better solutions.
@tjhei -- If you would like to, you could also share your scripts here which you use to create the yearly publication reports.
=> Added doi2bib script.

publications-2023.bib
This entry previously referred to `https://www.dealii.org/10.48550/ARXIV.2308.01651` which of course does not exist.
=> Fix preprint link.

Jenkinsfile
I tend to have the `https://doi.org/` part in DOI fields. This can be checked automatically via the CI. The same holds for using numbers for `month`.
This will fail because #564 isn't merged yet. I'll rebase after that is merged.
=> Augment CI checks.

publications-2023.bib
In #575 I have added an article that actually does not use deal.II. Mea culpa.
They cited the parallel hp article and I guess I got too excited about that.
=> Remove article that doesn't use deal.II

publications-2018.bib, publications-2019.bib, publications-2020.bib, publications-2021.bib
Part of #289. Follow-up to #536.
When I feel too sleepy to program in the morning, I made it a habit to update a few of our preprints in the publication list to help me wake up. Little by little I made it through the 2018 publications, which contained lots of duplicates.
This patch effectively removes 15 articles from the 2018 list, either by moving them to the correct year or by removing duplicates. Thus 2018 will fall from second to fourth place in the list of the years with the most publications.
=> Update preprints for 2018.

publications.include
We never updated the publications list for the 9.6 release paper.
=> Make sure the 9.6 release paper is listed at the top.

offline/publication_list.tex, publications-2024.bib, publications-2025.bib, publications-2026.bib
Unfortunately, the articles introduced in #645 were already part of the publication list. This patch removes them again.
This patch also introduces the first article for 2026. The histogram on the website has been adjusted with https://github.com/dealii/website/commit/15863a6624e83376e6064bd86e7f5a1141bb38ee.
=> Added 8 articles. Updated 1 article. Removed 4 duplicates.
